### ISSUE TITLE
JavaScript: use @2x assets

### ISSUE THREAD

**Issue by frogg** [Bestes-SPD-Hackathon-Team/Schulzzug-iOS-JS#1]
Provide @2x assets and use them in javascript for hdpi devices

**Comment by 5chdn** [comment]
The assets are all available in 2x resolution in `assets/` (those without `.50`). Just someone figure out how to tell phaser how to handle them.

**Comment by benmaier** [comment]
`:%s/.50//g`

:)

**Comment by 5chdn** [comment]
danger zone xD
